# db config
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 35MB
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.144:3306/team_e
    username: team_e
    password: green502

# mybatis config
mybatis:
  type-aliases-package: com.green.growgreen
  mapper-locations: mapper/**/*.xml

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: D:/download/
